### ISSUE TITLE
Sample game with beautiful pixel art

### ISSUE THREAD

**Issue by zachlatta** [hackclub/gamelab#26]
Create a sample game showing off Game Lab's features with beautiful, gorgeous, drop dead amazing pixel art to knock everyone's socks off.

- Should be fun to play
- Should have beautiful pixel art
- Should have great sound and feel like it has a well-rounded "aesthetic"
- Code should be readable by a JS beginner for inspiration in their own Game Lab games

**Comment by cedric-h** [comment]
![image](https://user-images.githubusercontent.com/25539554/151994745-23cb2af2-cc38-4bab-b520-dad47663f177.png)

artist contracted, tileset made.

grappling with a way to fit the tileset into game editor that has simple, readable code but is also easily extensible by club members.

storing the map as an ASCII string makes sense, but code to select the right tile based on which of its neighbors are occupied would likely be too overwhelming for beginners; we need the example to have readable code.

one option is to simplify the tileset, or to integrate a tile editor.
I still haven't decided exactly how I want to tackle this, but first I'm writing the code to decide the appearance of a tile based on its neighbors, to see how much I can simplify it and attempt to make it readable for beginners.

**Comment by zachlatta** [comment]
The game has been completed!
