### ISSUE TITLE
Bugs + versioning!

### ISSUE THREAD

**Issue by zachlatta** [hackclub/gamelab#27]
Fix all the bugs we can for a 1.0 launch! Please link issues for bugs that we find and fix to this one so we have a record of everything getting knocked out.

**Comment by leomcelroy** [comment]
January 31st 2022

- Max and I created a server for past releases of game-lab.
- I fixed the bug involving the renaming of assets.
- I added uploading of assets (sequencer tunes and pngs) with the assistance of Ian's PR.

**Comment by zachlatta** [comment]
Feel great about where we ended with this. Closing!
