### ISSUE TITLE
Themed interface with sounds

### ISSUE THREAD

**Issue by zachlatta** [hackclub/gamelab#28]
Once #25 is knocked out and we have some ideas for what the editor will be called, what it should look, and what it should feel like, style the interface and add sounds to make it really fun and playful.

Ideas for a couple things:

- What if there was some sort of really cool boot-up animation and a boot-up sound?
- I think there should be some sort of card when people first load Game Lab explaining what it is and how to use it
- Somewhere there should be some sort of documentation link

**Comment by maxwofford** [comment]
Yesterday had a call with @eilla1 @bellesea @sampoder to come up with a design. Rough draft in: https://www.figma.com/file/Iy67hEP6Git9SfrxPy3xeN/game-lab-UI-designs?node-id=0%3A1

Screenshot at time of writing this is here:

<img width="385" alt="Screen Shot 2022-02-01 at 10 02 26" src="https://user-images.githubusercontent.com/5891442/151993315-8c9445bf-2f83-4605-828c-34360903bb78.png">

<img width="386" alt="Screen Shot 2022-02-01 at 10 02 21" src="https://user-images.githubusercontent.com/5891442/151993289-926e596f-ff41-4d67-8d92-51ae7714bde4.png">

---

There's still a lot to do, but this is a good start. A [project naming bar was implemented](https://github.com/hackclub/game-lab/pull/31/commits/05e3d4c62ecc5daf87e9183d9196e0a382121ac7) in the same theme, but I think I'll need to break this into a couple issues to get done in time.

**Comment by zachlatta** [comment]
This happened! Thought where we ended up with for 1.0 was great. Closing.
