### ISSUE TITLE
Bug bounty flow

### ISSUE THREAD

**Issue by zachlatta** [hackclub/gamelab#29]
Build out flow in the frontend that communicates to the user that if they find and file a bug in Game Lab, we will send them candy! Or tiny plastic hands or something.

Ideally the flow would create whatever our current equivalent of a mail mission and assign it to someone to make sure the candy gets sent out.

**Comment by maxwofford** [comment]
Notes from a call with @YodaLightsabr:

- game engine version
- instance of code (+ sprites & tunes)
- previous dispatch events (?)
- previous global errors (not sure how to do this?)
- extra description fields
- optional address fields (we'll ship either tiny plastic hands or candy if we verify the bug)
- ip
- browser details (user agent, etc.)

**Comment by maxwofford** [comment]
#37 was just merged into dev. Still need to test it, but looks like we're getting the content of their page. Next step is to work on a mailing flow.

**Comment by maxwofford** [comment]
Quick update: form is broken in development, but works in production. Still need to make a mailing flow.

**Comment by maxwofford** [comment]
Here's the leftover stuff:

- fix the submission button which currently hangs forever (has something to do with the window.location.hostname line)
- have async logic so the form will pop open no matter what after 10 sec maximum (ie. if an async field fails to load). It should be resistant to errors on the page or during the submission process (the user is clicking the button once something has gone wrong on the page, so let's expect that)
- submitted forms should send a notice to `clubs+gamelab@hackclub.com` w/ a link to the airtable submission
- ask for user address in the form (make it clear it's optional, but i think it'll reduce the back-and-forth of messages after a bug report is filed)

@YodaLightsabr, are you up to take that?

**Comment by YodaLightsabr** [comment]
Sure. I was also thinking of some sort of redundancy to make sure that it works, and that sounds good. Maybe we could also store the bug report function in the global scope in case dispatch.js fails.

**Comment by maxwofford** [comment]
Thanks so much! I think [`9eaa3f5` (#31)](https://github.com/hackclub/game-lab/pull/31/commits/9eaa3f5bc33d167eecd7a31a6c0b31bffd28dd24) addresses the issue with s3 submissions, so don't worry about that

**Comment by YodaLightsabr** [comment]
I just realized that the original bug reporting feature is on #31. Should I continue work there, or wait for it to be merged to dev?

**Comment by zachlatta** [comment]
Closing! We got this done!
