### ISSUE TITLE
Killer branded README

### ISSUE THREAD

**Issue by zachlatta** [hackclub/gamelab#30]
Create an amazing README that communicates:

- What Game Lab is
- How it's intended to be used
- How it's different from Kaboom.js and other things like it (why did we create Game Lab instead of just using Kaboom.js or another alternative?)
- Immediately how to get started making a game and how to get help when you get stuck

The vibe should be:

- Fun / playful
- Straight to the point / not longwinded
- The sort of thing that can frontpage on Hacker News

**Comment by leomcelroy** [comment]
January 31st 2022

- I merged Zach's pass on my original README
