### ISSUE TITLE
Add view-only mode for embedding projects

### ISSUE THREAD

**Issue by YodaLightsabr** [hackclub/gamelab#33]
Feature idea: Add a view-only mode for embedding in projects or sharing with people.

@cedric-h had the idea of a place for people to share projects made, for people that participate in Hack Club and will be running game lab in clubs but are not in the slack. In order for it to function, there would need to be a mode where you only see the output so it could be embedded somewhere.

**Comment by maxwofford** [comment]
Looks like this was added in https://github.com/hackclub/gamelab/commit/1d81149b209c43f12438c09da4456be123d4eadd#diff-81ee83b87bb27545a57b76a603c2b5ecbbd39e98e90a5366124af026849294c5R172-R181. Closing for now!
