### ISSUE TITLE
Asset tooltips

### ISSUE THREAD

**Issue by maxwofford** [hackclub/gamelab#43]
Currently tooltips on assets are broken:

https://user-images.githubusercontent.com/5891442/152048445-8266b9e2-0a90-4c82-9723-78b25ffbed56.mov

- "Add sprite" tooltip floats super high above the button
- "Add tune" tooltip is hidden under the game preview
- Removing an asset (the red `x` buttons) should have a tooltip that says something along the lines of "remove"

**Comment by cedric-h** [comment]
in Chrome I don't see the tooltips at all

same in Safari

we have the text on the buttons now though, so I think that's better; closing the issue.
