### ISSUE TITLE
game gallery

### ISSUE THREAD

**Issue by zfogg** [hackclub/gamelab#5]
it would be cool to have a gallery of other games that people have submitted that one may choose to load rather than the default pong game.

there could be a simple star and comment system like scratch has.

we could use a slack channel as the backend like #ship-gamelab or something and store the comments and reacts on posts there and use slack auth to submit games via the gamelab website with your hack club slack account

**Comment by maxwofford** [comment]
Closing this, as we're using https://scrapbook.hackclub.com/r/gamelab
