### ISSUE TITLE
"An old game has been found" notification should say just how "old" the game is

### ISSUE THREAD

**Issue by cedric-h** [hackclub/gamelab#68]
i.e.
"a game from three hours ago was found ..."
vs.
"a game from two months ago was found ..."

**Comment by maxwofford** [comment]
Triaging this IRL with @cedric-h:
Closing b/c the intent of this was to tell which game a file is for & the UI now shows game names:
<img width="604" alt="Screen Shot 2022-04-08 at 12 27 04" src="https://user-images.githubusercontent.com/5891442/162483390-5ef033d1-8a55-4640-8f3d-617e91cb22b5.png">
