### ISSUE TITLE
Small grammar tweaks to Philosophy section in README

### ISSUE THREAD

**Issue by jessicard** [hackclub/gamelab#74]
Under https://github.com/hackclub/gamelab#philosophy, there's a few grammar tweaks that could be made.

Right now it reads:
> As we said before people learn best when they make things that they care about which they can share with others. This learning philosophy is called [constructionism](https://en.wikipedia.org/wiki/Constructionism_(learning_theory)) and Game Lab is a type of microworld. It's an environment where you can discover programming by using it to express yourself.

And maybe it could be:
> As we have said previously, people learn best when they make things that they care about, which they can then share with others. This type of learning philosophy is called [constructionism](https://en.wikipedia.org/wiki/Constructionism_(learning_theory)), and Game Lab is a type of microworld. A microworld is an environment where you can discover programming by using it to express yourself.

**Comment by abbyfischler** [comment]
#78
