### ISSUE TITLE
UI updates?

### ISSUE THREAD

**Issue by micahlt** [hackclub/gamelab#8]
I'm interested in possibly contributing to some UI updates here, but I was wondering what the goals exactly of this project are.  Is the basic aesthetic intentional, or would a more modern interface closer to something like [Replit](https://replit.com/) be appreciated?

**Comment by sampoder** [comment]
Personally, I think if the game-lab looked like Muse: https://github.com/hackclub/muse that'd be nice.

**Comment by sampoder** [comment]
^^ if we could pull it off really well that'd be epic

**Comment by sampoder** [comment]
I think that'd be great, but that'd probably be a question for @leomcelroy & @cedric-h, they're maintaining and building the repo

**Comment by micahlt** [comment]
All right, I'll wait for their input!  Memphis Hack Club just finished our workshop using Game Lab.  It's a great tool for beginners learning JavaScript 😄

**Comment by leomcelroy** [comment]
@micahlt Definitely open to PRs on this and Muse. Really glad you enjoyed it.

**Comment by maxwofford** [comment]
@micahlt I'm starting on a UI overhaul & would love to work with you if you're interested. Hit me up on the Slack!

**Comment by YodaLightsabr** [comment]
If you need another hand I'd also be happy to help.

**Comment by cedric-h** [comment]
There's always more work to be done in this category, but we've made some major progress here, so I'm going to go ahead and close the issue.
