### ISSUE TITLE
Add ability to mirror sprites

### ISSUE THREAD

**Issue by jessicard** [hackclub/gamelab#81]
It would be nice if I could mirror sprites on the x or y axis, as right now I am just adding sprites for walking left vs right.

**Comment by maxwofford** [comment]
Seems like this was fixed in https://github.com/hackclub/gamelab/commit/3bdbd9dd1b2fc8857bb9b875d74e8be223c7783d. Reopen if there's anything else that needs to happen!

**Comment by maxwofford** [comment]
<img width="883" alt="Screen Shot 2022-04-08 at 12 06 34" src="https://user-images.githubusercontent.com/5891442/162480379-3b2608c1-fcf6-4ad1-8659-8749737979b6.png">
